spring:
  application:
    name: stock_portfolio_svc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/${STOCK_PORTFOLIO_DB}
    username: ${STOCK_PORTFOLIO_USER}
    password: ${STOCK_PORTFOLIO_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    com.sahil.stock.portfolio: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
